#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranProfileId.h"


@protocol SystranLanguagePair
@end

@interface SystranLanguagePair : SystranObject

/* Source language [optional]
 */
@property(nonatomic) NSString* source;
/* Target language [optional]
 */
@property(nonatomic) NSString* target;
/* Array of profile identifiers [optional]
 */
@property(nonatomic) NSArray<SystranProfileId>* profiles;

@end
