#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranErrorResponse.h"


@protocol SystranTranslationStatus
@end

@interface SystranTranslationStatus : SystranObject

/* Error of the request [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Batch Identifier [optional]
 */
@property(nonatomic) NSString* batchId;
/* Is the request cancelled [optional]
 */
@property(nonatomic) NSNumber* cancelled;
/* Creation time of the request (ms since the Epoch) 
 */
@property(nonatomic) NSNumber* createdAt;
/* Description 
 */
@property(nonatomic) NSString* _description;
/* Expiration time of the request (ms since the Epoch) 
 */
@property(nonatomic) NSNumber* expireAt;
/* Completion time of the request (ms since the Epoch) [optional]
 */
@property(nonatomic) NSNumber* finishedAt;
/* Number of finished steps 
 */
@property(nonatomic) NSNumber* finishedSteps;
/* Status of the request 
 */
@property(nonatomic) NSString* status;
/* Number of steps to complete 
 */
@property(nonatomic) NSNumber* totalSteps;

@end
