#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranBatchRequest
@end

@interface SystranBatchRequest : SystranObject

/* Request identifier 
 */
@property(nonatomic) NSString* _id;
/* Status of the request 
 */
@property(nonatomic) NSString* status;

@end
