#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranProfile.h"
#import "SystranErrorResponse.h"


@protocol SystranProfilesResponse
@end

@interface SystranProfilesResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of profiles 
 */
@property(nonatomic) NSArray<SystranProfile>* profiles;

@end
