#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranLanguagePair.h"
#import "SystranErrorResponse.h"


@protocol SystranSupportedLanguageResponse
@end

@interface SystranSupportedLanguageResponse : SystranObject

/* Warning at request level [optional]
 */
@property(nonatomic) NSString* warning;
/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of language pairs [optional]
 */
@property(nonatomic) NSArray<SystranLanguagePair>* languagePairs;

@end
