#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranProfile
@end

@interface SystranProfile : SystranObject

/* Profile identifier 
 */
@property(nonatomic) NSNumber* _id;
/* Localization of the profile name [optional]
 */
@property(nonatomic) NSObject* localization;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Source 
 */
@property(nonatomic) NSString* source;
/* Target 
 */
@property(nonatomic) NSString* target;

@end
