#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranProfileId
@end

@interface SystranProfileId : SystranObject

/* Profile identifier 
 */
@property(nonatomic) NSNumber* _id;
/* Public or private profile 
 */
@property(nonatomic) NSNumber* private;

@end
