#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranErrorResponse
@end

@interface SystranErrorResponse : SystranObject

/* Readable description of the error 
 */
@property(nonatomic) NSString* message;
/* Additional information about the error [optional]
 */
@property(nonatomic) NSObject* info;

@end
