#import <Foundation/Foundation.h>
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranCrossDomainApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranCrossDomainApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranCrossDomainApi*) sharedAPI;
///
///
/// Silverlight client access policy file
/// Silverlight client access policy file (clientaccesspolicy.xml) to handle cross-domain requests.
///
/// 
///
/// @return NSURL*
-(NSNumber*) clientaccesspolicyXmlGetWithCompletionBlock :
    (void (^)(NSURL* output, NSError* error))completionBlock;
    


///
///
/// Adobe Flash cross-domain policy file
/// Adobe Flash cross-domain policy file (crossdomain.xml) to handle cross-domain requests.
///
/// 
///
/// @return NSURL*
-(NSNumber*) crossdomainXmlGetWithCompletionBlock :
    (void (^)(NSURL* output, NSError* error))completionBlock;
    



@end
